### ISSUE TITLE
Issue using the Mirage Component in the Ember Data section

### ISSUE THREAD

**Issue by JonForest** [emberjs/guides#1062]
The content of ```app/mirage/config.js``` is shown as:
```
this.get('/rentals', function() {
    return {
      data: [{
        type: "rentals",
....
```

When I use this, I get the following output in my Chrome console:
>WARNING: Encountered "data" in payload, but no model was found for model name "datum" (resolved model name using super-rentals@serializer:-rest:.modelNameFromPayloadKey("data"))

I changed ```data``` to ```rentals``` in the rentals array. I.e.
```
this.get('/rentals', function() {
    return {
      rentals: [{
        type: "rentals",
....
```

In the sample data used in the config.js, the data required is organised like this:

````
type: "rentals",
id: 2,
attributes: {
   title: "Urban Living",
   ....
}
```

The model and data usage is set up to work without the attributes nested object, like
````
type: "rentals",
id: 2,
title: "Urban Living",
 ....
}
```

I don't know enough yet to understand what the best practice solution for that is; whether there should be a different model definition, some kind of transform, or if for the sake of the tutorial whether we should just change the data format.
I'm changing the data format so I can continue.

**Comment by locks** [comment]
It seems like you are using Ember Data 1.x, which has RESTAdapter as the default adapter. You need to update your Ember Data to 2.x, which uses JSONAPIAdapter as the default instead.

**Comment by JonForest** [comment]
Ah.. thank you.  Would have been helpful if that's the version the Ember CLI component listed in the guides actually installed.

**Comment by locks** [comment]
@JonForest it's a long story :\

**Comment by JonForest** [comment]
:+1:  I should probably spend more time googling this, but how do I update the Ember data component?  I updated the versions to 2.2.0 in the package.json and re-ran npm.  Still no dice with the {data:...} rentals structure.

**Comment by locks** [comment]
It's the `bower.json` that at the moment controls the version of the libraries that are used.

**Comment by rtablada** [comment]
@locks thoughts on maybe running `ember g adapter application` and explicitly setting `DS.JSONAPIAdapter`? I think it's best practice to have an adapter created to allow for `host` and `namespace` customization later down the road anyway.

**Comment by JonForest** [comment]
@locks - Cheers.  That's got it after installing Bower and a bit of updating various versions.  Not quite sure what the solution is, but I reckon everyone following the guide as a brand new introduction to Ember will run into this.

**Comment by michaelrkn** [comment]
@rtablada Generally we try to stick to the "happiest path"/least amount of configuration in the Guides. Until we actually want to explain how to customize something, we'll stick with the defaults. We're in an unfortunate situation with Ember CLI right now, but that should be resolved before too long. Also, the Guides do include [instructions on upgrading to the correct versions](http://guides.emberjs.com/v2.2.0/getting-started/ember-cli/#toc_upgrading-ember).

**Comment by zachfedor** [comment]
@michaelrkn I totally agree that the path of least resistance should be explained in the Ember guides. That's a perfect philosophy for beginner's to get up and running. 

However, as a beginner I'm tripping all over myself because I haven't explicitly created an adapter to get Ember Data up and running (similar to what @rtablada was proposing). Going through the basic tutorial for Ember 2.2.0, my app is failing to load in the browser. According to Bower, I'm on version 2.2.0 for both Ember and Ember Data. I'm also using the most up to date version of Ember CLI by cloning the git repo and running `npm link`. Right now, that's version 2.2.0-beta.1-master-e803ac7fa6.

I have removed the `rentals` object in `routes/index.js` and replaced it with the `findAll` method. I have configured a route in Mirage's config to return the rentals instead. There is no error when `ember s` is building the project, but it won't load in the browser. When I try to visit `localhost:4200`, I get the following console errors:

* `Failed to load resource: the server responded with a status of 404 (Not Found)` on the /rentals route
* `Error while processing route: index Adapter operation failed Error: Adapter operation failed`
* `Error: Adapter operation failed`

Am I missing something?

**Comment by michaelrkn** [comment]
@zachfedor Try posting on Stack Overflow with your Mirage config and a link to your project on Github. Feel free to ping me on Slack and I can take a look.

**Comment by zachfedor** [comment]
I just used `ember g adapter application` and it created a RESTAdapter, even though I'm on 2.2 across the board. This leads to the original issue that @JonForest faced. I manually changed that to use JSONAPIAdapter and all is well.

Here is the [StackOverflow question](http://stackoverflow.com/questions/34339280/basic-ember-app-not-working-with-default-adapter).

I can create a separate issue here if this should be it's own thing.

**Comment by DSheffield** [comment]
Could somebody please explain how to get the tutorial working?  I'm another ember beginner that's run into this problem.  Followed all the discussion here, and now I don't get any errors but no data is displayed.

I've been going around in circles on this for several hours now, and this is a bit ridiculous that one of the first steps in the basic tutorial doesn't work.

**Comment by rtablada** [comment]
@DSheffield can you check your console and let us know if you have any information in the console?

**Comment by JonForest** [comment]
@Dsheffield I'm a bit flat out right now fitting a door. But I'm happy to
lend a hand tomorrow a little earlier than now if it helps? I'll see if I
can get on the slack channel later.

**Comment by michaelrkn** [comment]
Hey folks - this isn't a great medium to ask for tech help with the tutorial. The [Slack channel](embercommunity.slack.com) or Stack Overflow are more appropriate. Thanks!
