### ISSUE TITLE
Update "Upgrading Ember" section for Ember CLI 2.x

### ISSUE THREAD

**Issue by locks** [emberjs/guides#1094]
https://guides.emberjs.com/v2.2.0/getting-started/ember-cli/#toc_upgrading-ember needs to be updated for Ember CLI 2.x.

I consider this to be a blocker for the merging and releasing of 2.3 guides.

**Comment by rtablada** [comment]
Are we hinging this on a stable release or will 2.3 guides ship with a beta CLI?

**Comment by locks** [comment]
@rtablada stable Ember CLI 2.x

**Comment by rwjblue** [comment]
For Ember 2.3.0 and Ember Data 2.3.0, we need to change to indicate that users should update `ember-data` in `package.json` (and not `bower.json`).

**Comment by locks** [comment]
And for the 2.2.0 releases?

**Comment by rwjblue** [comment]
2.2.0 releases still need to be updated in `bower.json` as the current section suggests

**Comment by rwjblue** [comment]
I'll try to tackle this early in the week.

**Comment by toobulkeh** [comment]
Might I suggest including a small paragraph [here](https://guides.emberjs.com/v2.2.0/getting-started/#toc_installation) before saying "you're good to go"?

It's misleading and hidden otherwise, and has caused us a lot more trouble than it's worth.

I realize it would make the homepage more wordy, but it's a bit misleading to not have those steps there, since everything is lagging behind so much still, and those 2 commands don't give you the latest ember releases.

**Comment by rtablada** [comment]
@toobulkeh I that page is referring to installing Ember CLI and don't talk about working within an actual project.

**Comment by toobulkeh** [comment]
I disagree -- that page is Ember's guide to "installing Ember". It says nothing about installing the latest/proper version of Ember. It's been that way for 5+ months too -- which is when Ember 2.0.0-prod was released.
