### ISSUE TITLE
Ember Data guide issue

### ISSUE THREAD

**Issue by tyleryasaka** [emberjs/guides#1119]
I ran into an issue following the [Ember Data](https://guides.emberjs.com/v2.2.0/tutorial/ember-data/) guide (in the Tutorial section) where the data was not being loaded from mirage. I found that the issue was that the JSON API Serializer was not being used, causing the data to be read incorrectly (see console error message below). Once I specified that that JSON API be used as the serializer, the problem was solved (see code below).

The browser console error message:

>'WARNING: Encountered "data" in payload, but no model was found for model name "datum" (resolved model name using super-rentals@serializer:-rest:.modelNameFromPayloadKey("data"))'.

The code I added to app/serializers/application.js to fix the issue:
```
import DS from 'ember-data';

export default DS.JSONAPISerializer.extend({});
```
Aside from the issue that the tutorial did not work as expected, I am wondering why the JSON API serializer was not being used by default as is stated in the [docs](https://guides.emberjs.com/v2.2.0/models/customizing-serializers/)?

This is no longer an issue for me personally as I have found how to fix it. I just wanted to make the issue known (assuming it is an issue rather than an oversight on my part, which is entirely possible as this is my first day using Ember.js).

**Comment by HeroicEric** [comment]
@tyleryasaka The JSON API adapter and serializer weren't used by default until ember-data 2.0+. I'm guessing you're still using ember-data 1.13.15, since that's what is provided by default in a new app generated with the latest release of ember-cli (v1.13.13).

I think we should either update the tutorial to include the step of updating ember-data or specifying the adapter/serializer.

Also worth noting that once ember-cli 2.x ships, ember-data 2.x will be the default

**Comment by michaelrkn** [comment]
Looks like you missed the section on [upgrading to the latest version of Ember Data](https://guides.emberjs.com/v2.2.0/getting-started/ember-cli/#toc_upgrading-ember).

**Comment by tyleryasaka** [comment]
Yep I totally missed that. My bad.
