### ISSUE TITLE
Warn users they are reading old documentation for < V2.0

### ISSUE THREAD

**Issue by mozeryansky** [emberjs/guides#1122]
After reading a few pages of the guide for 1.10 I realized that I was on the wrong version. Is there a way the guides could warn readers they are reading old versions? Maybe something like symfony does: http://symfony.com/legacy

I was taken to the guide from google searching and started reading about resource and route and was very confused.

**Comment by mozeryansky** [comment]
Ha, I just saw that all 2.0 versions do warn that I'm reading old document but not for 1.0 versions. Could a change be made to the old versions to include this warning as well? (Would you welcome a pull request?)

**Comment by michaelrkn** [comment]
Thanks for getting involved here, @mozeryansky! A pull request would be very welcome, but this is a thorny issue. Old versions of the Guides are [generally not updated](https://github.com/emberjs/guides/blob/master/CONTRIBUTING.md). We've made exceptions for a couple important changes, such as this. However, backporting can involve difficult rebasing, and the person who [implemented the old version warning](https://github.com/emberjs/guides/pull/709) gave up trying to backport it before 2.0 because of rebasing conflicts. 

The "right" approach is to fix #934 so that we can easily backport JavaScript updates.

Alternatively, you could try to backport the existing old version warning code and fight the rebasing fight. I suppose instead of rebasing you could just copy the code over and make a new commit. This might actually be the easiest way.

The choice is yours :)

**Comment by mozeryansky** [comment]
I've having a ton of issues with ruby but I'll attempt to `copy the code over and make a new commit` if I can test it locally.

**Comment by michaelrkn** [comment]
There are likely folks in the [documentation slack](https://embercommunity.slack.com/messages/documentation/) who can help you out with your Ruby woes.

**Comment by mozeryansky** [comment]
Thanks, I'm using RVM instead of OS X's native ruby. Plus I need to use different command line tools `sudo xcode-select -switch /Library/Developer/CommandLineTools`. Macport isn't happy with that, but all is good. I literally just got the middleman server running.

**Comment by mozeryansky** [comment]
I don't know if you get a notification for references, but I attempted the fix and sent a pull request

**Comment by mdentremont** [comment]
Wooot, looks fixed to me!
<img width="983" alt="screen shot 2016-01-12 at 10 07 03 am" src="https://cloud.githubusercontent.com/assets/1106324/12265606/5760ad54-b914-11e5-84a0-e08ae5a3b908.png">

**Comment by locks** [comment]
@mdentremont you're on v2.0.0, this is for < v1.13.0

**Comment by locks** [comment]
Closed until @acorncom saves us with the single build refactoring.
