### ISSUE TITLE
Mirage tutorial step code example has an error

### ISSUE THREAD

**Issue by ioev** [emberjs/guides#1149]
https://guides.emberjs.com/v2.2.0/tutorial/ember-data/

The code example for "Let's now configure Mirage to send back our rentals that we had defined above by updating" returns an object with a "data" property.  The Ember Chrome plugin console will complain that there are no models with the name "datum".  Changing this property to "rentals" fixes the example.

Edit:  Sorry, I just realized that my version of Ember is 1.13.13, which is likely not compatible with this tutorial.  This was the version that was installed while I was following command-for-command along with the tutorial.

**Comment by locks** [comment]
Yes, this is a problem with `npm install -g ember-cli` installing Ember CLI 1.13.13 instead of the latest 2.2.0 beta. This means that the Ember Data version will be 1.13.x, and in this version the default adapter is RESTAdapter, hence it trying to find the `datum` model.
In Ember Data 2.x.x, the default adapter is JSONAPIAdapter, which uses the format in the tutorial.
