### ISSUE TITLE
Core Concepts lacking notes about Controllers

### ISSUE THREAD

**Issue by jsmestad** [emberjs/guides#1162]
It seems that controllers are still required as part of the Ember.JS stack. However the current [Core Concepts](https://guides.emberjs.com/v2.2.0/getting-started/core-concepts/) page has no reference to controllers even for usage with things like Query Parameters. Is this an oversight or intentional?

I was surprised going through the guides section by section to see Controllers start to pop up without much explanation as to their role in the Ember stack

**Comment by locks** [comment]
This is intentional as controllers play less of a significant role in the stack nowadays, and they are going to evolve into routable components somewhere down the 2.x branch. Which is mostly what's explained in the introduction of controllers.

The current limbo until routable components land made us do some compromises in the guides.

**Comment by jsmestad** [comment]
Thanks for the clarification @locks
