### ISSUE TITLE
Header on guides tab is styled differently than other emberjs.com tabs

### ISSUE THREAD

**Issue by mdentremont** [emberjs/guides#1167]
Very minor, but just noticed that on https://guides.emberjs.com/v2.2.0/ has a different header than any other tab on Emberjs.com (see screenshots). Also, when on https://guides.emberjs.com/v2.2.0/, the "Guides" tab is not styled to show that "Guides" is selected.

<img width="684" alt="screen shot 2016-01-12 at 10 08 53 am" src="https://cloud.githubusercontent.com/assets/1106324/12265651/9461f5d2-b914-11e5-9a7c-f621bd496229.png">
<img width="790" alt="screen shot 2016-01-12 at 10 08 47 am" src="https://cloud.githubusercontent.com/assets/1106324/12265653/96a7a58a-b914-11e5-8768-7181d3841c12.png">

**Comment by locks** [comment]
Yup, it's a bit jarring but it's due to our architecture. Each version of the guides is effectively its own website, hence the disparity. The older versions won't be fixed, but the website itself is going through the redesign process and will soon be matched. Thanks for raising the issue all the same!
