### ISSUE TITLE
EmberData and multi-word model names

### ISSUE THREAD

**Issue by samsebastian** [emberjs/guides#1192]
All the guides really only relate to a single word model name.

I'm pulling my hair out trying to figure out the right conventions by trial and error. 

At first I had models and API endpoints named like `contact.js`, `contact-group.js` but the relationships were refusing to link up even after they loaded and populated both models. 

I then found the issue below and went and renamed everything to camelCase ie `contact.js`, `contactGroup.js` as per instructions, but I keep getting the error `Error while processing route: contact.index No model was found for 'contactGroup' Error: No model was found for 'contactGroup'`

https://github.com/emberjs/website/issues/290

The only thing that has worked is naming everything like `contact.js`, `contactgroup.js` but I feel like that is contrary to the info in the guide linked in the above.

What would be good is some specific guidance on below:

- file name: big_mac.js or bigMac.js or big-mac.js ...?
- DS relations: DS:hasMany('bigMac') or DS:hasMany('big_mac') ...?
- DS.store: store.findRecord('bigMac') or store.findRecord('big_mac') ...?

If this is already duplicated somewhere else, apologies!

**Comment by locks** [comment]
Everything is dasherized.

**Comment by samsebastian** [comment]
One big thing that caught me out was that it wasn't immediately clear that if you want to use a trimmed down relationship name ie in contact model having `groups: DS.hasMany('contact-group')` means you need to match up to `"groups"` out of your API endpoint as the relationship *name* rather than `"contact-group`", but include `"contact-group"` as the *type*.

That is probably the biggest thing that gave me the most grief and would have been so easy to solve if that explanation had been in the guides. The JSONAPI docs don't really cover multi word or namespaced names either so I finally got it via trial and error.

**Comment by eccegordo** [comment]
@locks perhaps there needs a table that enumerates the specific conventions here including interesting corner cases. I think for many people a clear reference table would help. And probably makes sense to map to concrete examples that stem from the unit tests in ember JS, ember cli and ember data.

@samsebastian I have always used singular dasherized strings for model types. One thing to be aware of though are examples where the pluralization rules might not be intuitive or obvious. If the plural form seems really awkward to work with I sometimes stick "-item" on the end of the type name to get around odd pluralizations.

**Comment by samsebastian** [comment]
@eccegordo I thought the same, and just converted all my models singular dasherized now as well (coming from Laravel on the other side where Models are singular it seemed more natural), but I'm finding that the JSONAPI serializer in Ember seems to convert them to plurals in the payload when sending requests back?

ie `"relationships":{"groups":{"data":[{"type":"contact-groups","id":"22"}]}},"type":"contacts"}}` (note that `contact` and `contact-group` has been modified to plurals. 

The API on the other side seems to be smart enough to pick it up and convert it, but it seems odd that it is converting it to plurals somewhere in Ember. Because of that, I'm thinking maybe plurals is the right naming convention?

**Comment by eccegordo** [comment]
@samsebastian you raise a good point. 

> The API on the other side seems to be smart enough to pick it up and convert it, but it seems odd that it is converting it to plurals somewhere in Ember. Because of that, I'm thinking maybe plurals is the right naming convention?

*CAVEAT* I am not a regular ember data contributor so don't know the design intentions of the core team

But when I think about this, it seems logically consistent when you consider the following:

1.) Ember shares a convention over configuration design philosophy that owes a lot to Rails. And Rails has a lot of automagical pluralization behavior.

2.) Before JSON API went 1.0 the out of the box behavior of Ember Data was to work with Active Model Serializers and Rails conventions.

3.) The pluralization of the model type name on the server API endpoint makes semantic sense.
`example.com/api/contacts`
This endpoint represents all instances of the type `contact`
This resource endpoint is implicitly a collection of instances of type `contact` and therefore is implicitly represented as an array in JSON API, thus the pluralization.

Each individual instance needs to be identified by the `type` + `id`
`example.com/api/contacts/:id`
or
`example.com/api/contacts/123`

On the client side  (with Ember Data) it makes sense to talk about these as singular instances. Because every model record is pretty much guaranteed to have an id defined (for making the identity map work). Therefore you are almost always talking about instances and not necessarily collections of things.

The JSON API spec says

> Every resource object MUST contain an id member and a type member. The values of the id and type members MUST be strings.

> Within a given API, each resource object's type and id pair MUST identify a single, unique resource. (The set of URIs controlled by a server, or multiple servers acting as one, constitute an API.)

> The type member is used to describe resource objects that share common attributes and relationships.

http://jsonapi.org/format/#document-resource-objects

Later on in the spec they talk about responses and compound documents.

> Responses

> 200 OK

> A server MUST respond to a successful request to fetch an individual resource or resource collection with a 200 OK response.

> A server MUST respond to a successful request to fetch a resource collection with an array of resource objects or an empty array ([]) as the response document's primary data.

http://jsonapi.org/format/#fetching-resources-responses

The Ember Data model class describes the schema for an individual model instance. But does not necessarily describe the collection schema or semantics. Those are store level semantics, and ultimately something that the serializer and adapter layer must resolve depending on how conventional your API backend is.  Because of this I think it is fair to say that Ember Data is trying to normalize and resolve these store level semantics for you when it automatically pluralizes in the serializer. And probably the intent is to abstract away the store level details from routine Ember code. 

Where you can get into trouble though is when the pluralization rules are not straight forward and the `type` name is not what you expect. Which is why I like putting `-item` at the end of some of my types if I want to remove ambiguity. 

For example imagine I had a model  called `criterion`, would the serializer use `criterions` or `criteria`?

Other potential irregular cases

```
potato -> potatoes 
cactus -> cacti
analysis -> analyses
phenomenon -> phenomena
criterion -> criteria
person -> people
sheep -> sheep
deer -> deer
moose -> moose
```
@locks you might want to include a few irregular pluralization examples. I am not sure on the details of ED's pluralization library. The `analysis`, `phenomenon`, and `criterion` examples would be interesting. I could imagine those in real code. 

To my way of thinking if you pluralize the ember data model type you are introducing a subtle confusion between collection and instance. On the client side the store methods define how to work with the collection, but most of the time in Ember code you are working with model instances. e.g. a `contact` and not all `contacts`. 

On the server side the primary concern is what type of resource am I dealing with? Point me to its collection. And how do I persist this item among many to a persistence tier like a database? So you are working with the table of `contacts` and using the `id` to decide where in the table to SELECT, INSERT, UPDATE, or DELETE that record.

Of course there is nothing to strictly enforce the behavior on the server side, this is mostly just conventional patterns found in the Rails world. Other frameworks, server side stacks and projects may or may not share the same exact conventions. This is also why the adapter and serializer layers in Ember Data can serve as escape valves if you need to work around a non conventional backend. The front end client code gets to remain really stable and still work with very different types of backends and API designs.

Anyway, that is how I think about it. But would love people more close to the implementation details to document the theory part of this. 

The JSON API spec is pretty dense, it is almost like we need a condensed Cliff Notes guide to the spec and ember data internals. Something that gives the overview first before diving deep in the spec specifics.

The JSON API spec is really written for implementors and doesn't necessarily discuss this subject in a style well suited for people just coming into it, IMHO.

**Comment by locks** [comment]
@samsebastian just realized this is actually addressed in [relationship guide](https://guides.emberjs.com/v2.3.0/models/customizing-serializers/#toc_relationships):

> Any belongsTo relationships in the JSON representation should be the dasherized version of the property's name. For example, if you have a model:

**Comment by locks** [comment]
@eccegordo 
> 1.) Ember shares a convention over configuration design philosophy that owes a lot to Rails. And Rails has a lot of automagical pluralization behavior.

It's not automagical, it's [code](https://github.com/rails/rails/tree/master/activesupport/lib/active_support/inflector).

> [a lot of stuff about semantics]

From [Identification](http://jsonapi.org/format/#document-resource-object-identification):
> Note: This spec is agnostic about inflection rules, so the value of type can be either plural or singular. However, the same value should be used consistently throughout an implementation.

Ember Data expects the `type` key to be plural.

> @locks you might want to include a few irregular pluralization examples. I am not sure on the details of ED's pluralization library. The analysis, phenomenon, and criterion examples would be interesting. I could imagine those in real code.

That level of detail is for the [API documentation](http://emberjs.com/api/data/classes/Ember.Inflector.html).

> [JSON API spec analysis]

I recommend opening a separate issue if you wish to discuss how to address the explanation of Ember Data conventions.

**Comment by eccegordo** [comment]
@locks I think that inverse relationship information is slightly inconsistent or ambiguous in some corner cases unless you serialize some of the rules yourself under the meta key.

https://github.com/json-api/json-api/issues/804

Also, I didn't mean to be disparaging with my use of "automagical" I just meant that the implementation details were automatically handled (e.g. the inflector code). Someone not familiar with the details could be forgiven for thinking it is somewhat magical until they learn the implementation details.

> automagical ‎(comparative more automagical, superlative most automagical)

> Automatic, but with an apparent element of magic. Commonly used in computer and other technology fields, referring to complex technical processes hidden from the view of users or operators, resulting in tech that **just works**.
https://en.wiktionary.org/wiki/automagical

The consistency of the type key stuff is confusing to new comers myself included.

> Ember Data expects the type key to be plural.

That's all fine and good but we are not absolutely consistent on this

`var posts = this.store.findAll('post'); // => GET /posts`
https://guides.emberjs.com/v2.3.0/models/finding-records/#toc_retrieving-multiple-records

But I am NOT suggesting that the above should be changed to

`var posts = this.store.findAll('posts'); // => GET /posts`

Anyway you are right there is a longer more detailed conversation to be had in a different issue about ember data conventions.

**Comment by locks** [comment]
> That's all fine and good but we are not absolutely consistent on this

I was specifically talking about the `type` key in the payload. Like the adage goes, naming is one of the hardest problems! I'm not too keen on that convention myself, I inquired about it once but the logs are lost in Slack-land.

**Comment by eccegordo** [comment]
Ah ok. 

So what is the proper term for 'post' as in
`this.store.findAll('post');`

- Model type?
- Model name? 
- Model type key? 
- Model class name?

It seems that in most cases the model name is also the type key singularized, with some special cases when describing relationship keys (hasMany and belongsTo).

**Comment by samsebastian** [comment]
So as a new comer to Ember and JSONAPI spec, the thing that really broke things for me was implementing the relationship names incorrectly. 

I'm still not super clear if the convention is to make the relation name the same as the relation type, or if it's acceptable (from a pattern point of view), to use shortened versions of the type as the name.

Example
```
-- contact.js
groups: DS.hasMany('contact-group')
```
Which would mean I can access in template like `{{#each model.contact.groups as |group| }}`

Or if I should be defining it like:
```
-- contact.js
'contact-groups': DS.hasMany('contact-group')
```
Which would on the surface seem safer but mean I would have the use like `{{#each model.contact.contact-groups as |group|}}` which is uglier.

**Comment by eccegordo** [comment]
I don't believe the attribute name and the type keys have to be exactly the same. Just have to make sure you are consistent on the type keys when using stuff like model hooks and store methods. I personally would follow this pattern
```
'contactGroups': DS.hasMany('contact-group')
```
The plural form of the attr signals in your code that you are dealing with an array or hasMany. And the type key `contact-group` is consistent.

I do that in my project and it seems to work fine.

Conversely, if you can simplify things you might be better off

```
'groups': DS.hasMany('group')
```

Template code that reads

```
{{#each model.contact.groups as |group|}}
```
instead of 

```
{{#each model.contact.contactGroups as |group|}}
```

seems a little cleaner. But `group` might feel too generic depending on how many models you have in your project and if you think you might want different kinds of "groups" e.g `contact-group`, `user-group`, `support-group` etc.

Also, I don't believe model attributes are intended to be "kebob" cased but rather should be camelCased. In your template code you are dealing with attributes. In you route model hooks, and adapter/serializer logic you are dealing with types. But always dasherize or "kebob" case the type keys.

@locks is that the convention?

Dasherized attrs seems wrong.

**Comment by eccegordo** [comment]
Note that the default implementation in ember data JSON API serializer is going to automatically dasherize the model attribute.

https://github.com/emberjs/data/blob/v2.3.0/addon/serializers/json-api.js#L352

The dasherize behavior comes from Ember.String
http://emberjs.com/api/classes/Ember.String.html#method_dasherize

I believe that this means that if your code was under specified and looked like this

```
'contactGroups': DS.hasMany()
```

Ember Data would try to do the right thing and assume your type key was `contact-groups` 

However, you will be better off in the long run if you are consist and explicitly define your type keys in their dasherized form in your model classes.

If you find you actually need to customize your type keys and want the attributes to be different or arbitrary you can use `keyForAttribute` to customize the way your serializer works.
http://emberjs.com/api/data/classes/DS.JSONAPISerializer.html#method_keyForAttribute

**Comment by acorncom** [comment]
Closing this issue, as it seems like the take-away is "we need dasherized examples".  Will aim to add another issue to track that

**Comment by samsebastian** [comment]
From a new user perspective, it would also help to include a note explaining how whatever you use as your relationship name, needs to be mirrored on the JSONAPI response. 

Ie if you use the shorthand relationship *name* `groups` instead of matching the relationship *type* `contact-groups` the API needs to send the relationship name as `groups`. This was my biggest pain point because I was assuming the serializer would match it up based on the type rather than the abstract name, so I was sending the name incorrectly as the full model type name from the backend.

**Comment by locks** [comment]
@samsebastian where did that assumption come from? The thing on the left (whether attr or relationship) is the name that shows up in the payload, the name on the right (whether transform or model type) is what's used by Ember Data to make sense of the data. What I mean by this explanation is that both APIs behave the same way.

**Comment by samsebastian** [comment]
@locks 
Oh it was completely my bad, I wouldn't say it was necessarily based on anything other than perhaps assuming Ember did it's own magic around the arbitrary "name" of things, but the underlying connection / relationship was still defined and serialized on the more specific "type" when dropping to JSONAPI format. I'd say it was more from not really having any obvious guidelines and just taking a "best guess".

I'm certainly not trying to say the way it actually works doesn't make sense in hindsight or anything, my thoughts were more along the lines of "more information / examples is always better" when it comes to smoothing out the learning curve and making it as friendly as possible for a new user not familiar with the in depth specifics of JSONAPI conventions. 

I think Ember is such a great framework the more I learn, but from a dead stop (especially not having any modern frontend javascript experience to draw on), there are little things like this where although someone who has got past the initial learning curve would think it's elementary, a specific example would have really made things a lot less painful. It's not even that it would have been so hard in isolation, but when you are trying to find the right way to do "everything", little snippets of "the right way" are a godsend.

Ultimately, I think everyone should spend the time reading through the code and API etc to really understand *how* things work, but when you are weighing up a handful of different framework options and trying to prototype something up quickly, getting stuck on the basics / fundamentals can sometimes lead to just dropping it and never getting to the point where you do a full read through. I'm certainly glad I persevered and figured it out via trial and error, but I'm sure there would be a lot of people who get overwhelmed and give up.

**Comment by locks** [comment]
@samsebastian hi, are you still using Ember? I was reviewing my notebook and this was on it. If you could join us in the Slack `#-learning` channel to discuss improvements it would be very helpful to us.
