### ISSUE TITLE
Incorrect example in writing helpers

### ISSUE THREAD

**Issue by stocksr** [emberjs/guides#1318]
in source/localizable/templates/writing-helpers.md line 263 there is meant to be an example of a class based helper format, for the is-authenticated helper instead there is a copy of a previous example format-currency.

**Comment by acorncom** [comment]
Confirmed, things are currently worded a bit confusingly.  Looks like that's due to the insertion of the `is-authenticated` helper example **above** the `format-currency` instead of after it.  If we shift the example that was introduced in this https://github.com/emberjs/guides/commit/9e392679485d7cb412e7c62f706bdc873281210f to after the `format-currency` helper (and then introduce the aspect of using services) this should get much clearer ...
