### ISSUE TITLE
Building a complex component - why am I using a component?

### ISSUE THREAD

**Issue by bambery** [emberjs/guides#1529]
I am on the step of [creating a complex component](https://guides.emberjs.com/v2.6.0/tutorial/autocomplete-component/), but I am confused as to the value of this component. The component itself appears only to pass through the arguments to the controller, where the logic lives - even the `#each` for displaying results is on the index's template. 

Also, controllers are introduced for the first time in this page, but it is not explained why the logic for filtering lives on the index's controller. Could I not put this logic within the component so that the process of filtering is contained in the component (which is called `list-filter`)? Why did neither of the two other sample (simple) components so far use a controller (ie `people-list` and `rental-listing`)?

**Comment by toddjordan** [comment]
Hi @bambery thanks for the feedback.  I don't feel we need to change the example, but we possibly could explain it better.

"list-filter" is made to be a generic component, meaning its job is to take a function that returns a list of things based on a user input query.  The component provides the input query and simply invokes the closure action (function) based on the the value of the input, and yields the results to the component block.  The reason the results simply get yielded to the component block is because the component doesn't have an opinion in this case how the results get displayed (partly because it doesn't really know what its even displaying)

The reason the controller is brought in is because its the next level "up" that's going to provide the list of rentals. Since the `list-filter` doesn't really know about filters, we don't do a store query on them from within the component.  Similarly,  `rental-listing` doesn't do any data access because its data is passed in (originating from the route). Also, `rental-listing` doesn't invoke and actions "up" to the controller.

I'll take another pass at the tutorial section to make sure this is clear.

**Comment by AndriusZid** [comment]
Hi, I have an issue on this tutorial with filtering.

When I filter city, San in results i see only Grand Old Mansion, but when i delete filter field quickly I don't see all results, but in console.log I see that GET request returns correct results with all three cities. It seems that UI missed it and didn't updated as expected.

UI test are passed okay.

![filter-ui](https://cloud.githubusercontent.com/assets/8049177/17056162/3dddbfd2-501a-11e6-85bc-075c6ef41ab3.gif)

**Comment by toddjordan** [comment]
Hi @AndriusZid, thanks for reporting. can you open you comment in its own issue?

**Comment by AndriusZid** [comment]
Hi @toddjordan , opened new issue with same comment here #1572
