### ISSUE TITLE
Building a Complex Component - filtered results are not displayed on UI when typing/deleting fast

### ISSUE THREAD

**Issue by AndriusZid** [emberjs/guides#1572]
Hi, I have an issue on this tutorial with filtering.

When I filter city, San in results i see only Grand Old Mansion, but when i delete filter field quickly I don't see all results, but in console.log I see that GET request returns correct results with all three cities. It seems that UI missed it and didn't updated as expected.

UI test are passed okay.

![filter-ui](https://cloud.githubusercontent.com/assets/8049177/17056162/3dddbfd2-501a-11e6-85bc-075c6ef41ab3.gif)

**Comment by rogergl** [comment]
I would help, but I have one problem: The code looks absolutely valid to me ?

**Comment by toddjordan** [comment]
The code needs improvement because its asynchronous.  When you call to filter it goes through ember data and ultimately ajax calls, meaning the order that the results come back are not guaranteed.  One way to account for this is when the promise is fulfilled, to compare the query used for the search with the current value of the input field.   I've coded this into the super rentals repo in a [PR](https://github.com/ember-learn/super-rentals/issues/56).

Next step would be to update the guides to explain this.

**Comment by toddjordan** [comment]
added some defensive code to the tutorial.  The ultimate solution may be to use ember-concurrency, but we are waiting until we get a "beginner's tutorial" as part of the docs, so what we have can be an "advanced tutorial"
