### ISSUE TITLE
Google leads me too often into the older versions of the docs

### ISSUE THREAD

**Issue by motocarota** [emberjs/guides#1584]
I know It's partly my fault for not being more focused, but it happens frequently that I spend a good minutes reading old version of the docs sometimes with parts that now are totally deprecated.

This happens because google sends me directly into the docs, IMHO you should try to avoid this to help newcomers not getting confused, maybe discouraging search engines to crawl old versions of the docs or ...closing that sections entirely to them, I don't know.

Thank you!

**Comment by motocarota** [comment]
Another solution could consist in styling older version of the docs with a different visual

**Comment by locks** [comment]
We have a big red warning at the top of the page warning that it's an older version already, and anything below `v2.1.0` is pre-redesign so it's visually different. Bad Google results is an old and fuzzy problem that we have, but there isn't a clear solution still.
Since we're already tracking this in a [similar issue](https://github.com/emberjs/guides/issues/604), I am going to close this one. @acorncom can provide more detail.

**Comment by acorncom** [comment]
@motocarota Short answer is: we're working on it ;-)  Lots of details / background here (https://github.com/emberjs/guides/issues/1185) if you're interested.

TL/DR: We're adding better search to all older guides pages (https://github.com/emberjs/guides/issues/1561) so we don't totally strand folks on older versions of Ember.  Once that's done, we'll tell Google to only index `/current`, which doesn't exist yet but will, and will then ask Google to drop all older versions of the guides from its index.  Searching on Google will then only give you results from the current version.
