### ISSUE TITLE
Ember Inspector Introduction page isn't displayed

### ISSUE THREAD

**Issue by GavinJoyce** [emberjs/guides#1686]
I'm not sure what changed, but https://guides.emberjs.com/v2.8.0/ember-inspector/ is currently a 404.

`indroduction.md` was introduced in https://github.com/emberjs/guides/pull/1671 and it did display correctly on production for a few days. It also works on master locally:

<img width="780" alt="screen shot 2016-10-06 at 10 22 32" src="https://cloud.githubusercontent.com/assets/2526/19147168/d4f2b39e-8bae-11e6-8da6-cd3dbd41e1d8.png">

**Comment by GavinJoyce** [comment]
It seems to be back now. Is there anything that documents how the guides are deployed? I wonder if there is a bug.

I'll close this for now and reopen if I see this happen again

**Comment by locks** [comment]
@GavinJoyce https://github.com/emberjs/guides.emberjs.com/#publish let us know if we can add more detail

**Comment by GavinJoyce** [comment]
@locks thanks, I'll dig into it if it happens again

**Comment by acorncom** [comment]
@locks @GavinJoyce For this particular bug, I think it would have somehow been triggered by the file here (https://github.com/emberjs/guides/blob/master/.travis/continuous-delivery.sh) as Gavin's video was merged in 2.8 and then disappeared briefly.

Best guess is that another older PR was updated and somehow fiddled with our CI system.  But that shouldn't have happened because of the `on` guard for Travis seen here ... https://github.com/emberjs/guides/blob/master/.travis.yml#L11-L16
