### ISSUE TITLE
Nested routes / Ember cli generate

### ISSUE THREAD

**Issue by pat123456** [emberjs/guides#1703]
In Ember guide, chapter "[Defining your routes/Nested routes](https://guides.emberjs.com/v2.8.0/routing/defining-your-routes/#toc_nested-routes)" 

It is explain :
To generate the above nested route, run:
"ember generate route posts/new"
And then add the {{outlet}} helper to your template where you want the nested template to display:
(in templates/posts.hbs)

As explained, we think that with "ember generate route posts/new", the "templates/posts.hbs" should already be created.

The guide should tell that we have to run "ember generate route posts" before.

Or may be Ember cli should create all the needed routes automatically ?

**Comment by locks** [comment]
@pat123456 while the tutorial has a logic sequence because you're building an application, the rest of the Guides are more freeform. If you scroll to the top of that guide, we show you how to create a route, and then show a couple of "Basic Routes" examples.

How do you feel about https://github.com/emberjs/guides/pull/1704/files ?

**Comment by pat123456** [comment]
Yes, I think this will be enough to remove the confusion
Thank you for that !
