### ISSUE TITLE
Make ember-twiddle examples

### ISSUE THREAD

**Issue by gmarquet** [emberjs/guides#1814]
I think it will be nice to have ember-twiddle example on most of the pages.
The new ember users could see the functionalities/hierarchy/etc and test them without the hassle of the set up.
And maybe, later we can have a library on ember good practices with examples. 
This is something, that i think i can start.

I wanted to know your opinion.

**Comment by acorncom** [comment]
@gmarquet We would love to do this (and used to do it in old versions of the guides using JSBin).  Because yes, it would be a great starting point for new folks interested in Ember.

There are a few complexities we run into with this (which is why we don't use JSBin currently).  The primary one is that JSBin and Twiddles are both tied to individual user accounts.  What we've found over time is that maintenance becomes a substantial headache if/when we need to go update an example that was setup by someone no longer around that has been referenced across multiple versions of the guides.  Do we see if we can get the original submitter to update it for us, even if they have shifted ecosystems?  Do we fork the example and then have to update all versions of the guides?

As a result, what we've talked about is having our build system generate code samples from our examples in the guides using a format that Twiddle could read. We worked through some of this with Twiddle folks and they are willing to work with us on making those changes to Twiddle when the time comes.

But we'd probably wait to do this until the new module unification resolver (https://github.com/emberjs/rfcs/blob/master/text/0143-module-unification.md) lands so we don't have to do major work on revising this later.

Is that something you'd be interested in helping us work through / spear head?  We definitely need the help and manpower to do these types of things, so if you are, would love to collaborate on this together ...

**Comment by gmarquet** [comment]
@acorncom generate code for ember twiddle seems to be a great idea :)

Not sure if i can lead but i can certainly help. I'll take a look at the ember-twiddle project in the week-end.

**Comment by acorncom** [comment]
@gmarquet The main thing I think we'll need to do on this is work out how to extract all code samples from the guides markdown files as part of the build process in the guides repo.  The highlighter code (https://github.com/emberjs/guides/blob/master/lib/highlighter.rb) is probably the closest code we have to doing that.  Once we have something that can properly extract the code samples (JS and HBS files I would think) we would then need to come up with a good format that would work with Twiddle.  But that's a later stage to this process ...

**Comment by acorncom** [comment]
One other blocker on pursuing this to far is the lack of support for IE/Edge in Ember-Twiddle at the moment.  More details discussed at https://github.com/emberjs/website/issues/2369#issuecomment-289241630
