### ISSUE TITLE
Please use the ember-cli.com design for the ember guides.

### ISSUE THREAD

**Issue by lazaridis-com** [emberjs/guides#1849]
I just read through this:

https://ember-cli.com/user-guide/

The design has a far better readability than  https://guides.emberjs.com/v2.11.0/.

It would be nice if this design would be adopted by the main documentation, which hurts a bit my eyes...

Just open the 2 sites side-by-side, and you'll see the big difference in readability.

(to be fair: the code-boxes have a better readability on guides.emberjs.com )

**Comment by lazaridis-com** [comment]
(just the code-boxes have a better readability on guides.emberjs.com )

**Comment by lazaridis-com** [comment]
(a possibly quicker alternative is to switch to the original initial design https://guides.emberjs.com/v1.10.0)

**Comment by rwjblue** [comment]
It's much more likely that we will go the other way. 

> which hurts a bit my eyes...

If you could provided details on this, we are generally happy to address. We care deeply about the sites accessibility, and are always looking for ways to make it better. 

Without a more targeted / detailed explanation of _what_ is wrong this issue is not very actionable (and will likely end up closed).

**Comment by lazaridis-com** [comment]
@rwjblue
> We care deeply about the sites accessibility, and are always looking for ways to make it better.

Sounds impressive.
