### ISSUE TITLE
Deployment instructions are not documented

### ISSUE THREAD

**Issue by mixonic** [emberjs/guides#1850]
The guides for v2.12 of Ember have not been released, largely because it is not documented how one might perform a deployment. This must be covered in the README. For example the [website README documents deployment of API docs](https://github.com/emberjs/website#api-documentation).

**Comment by acorncom** [comment]
Hey @mixonic, deployment info has been generally left on https://github.com/emberjs/guides.emberjs.com (due to guides being split between two repos). There's a note about "RELEASING" at the bottom of the main Readme that links over to that, but due to our switch from Firebase -> Netlify prior to EmberConf those instructions weren't up-to-date.

Believe everything should be resolved at this point, does that look clear enough to you?

**Comment by acorncom** [comment]
_And yes, not having our code split between repos is something we would love to have resolved, it's turned out to be a cause of many headaches ..._

**Comment by acorncom** [comment]
Closing this as resolved, happy to reopen if more is needed
