### ISSUE TITLE
Tutorial may want to mention the Ember CLI move away from bower

### ISSUE THREAD

**Issue by RyanNerd** [emberjs/guides#1865]
As part of best practice for features that are slated or even in part have been deprecated such as `bower` it is helpful to mention this in the tutorial. For example at: https://github.com/emberjs/guides/blob/master/source/localizable/tutorial/ember-cli.md 

```md
**bower.json**: Bower is a dependency management tool.
It can be used to manage front-end plugins and component dependencies
(HTML, CSS, JavaScript, etc).  All Bower components are installed in the
`bower_components` directory. If we add front-end dependencies, such as 
Bootstrap, we will see them listed here, and added to the 
`bower_components` directory.
_Note_: Ember CLI is moving away from bower usage. We mention this now so you
can follow best practices, and to make you aware that this feature may be 
deprecated in the near future. 
```

**Comment by locks** [comment]
Hi @RyanNerd, thank you for your contribution. I appreciate the sentiment of wanting to move off of Bower, however, this characterisation has some potential problems.

We've found that saying something might get deprecated in the future is detrimental (hello controllers :X). Plans change, and we only deprecate when there is a migration strategy delineated, after an RFC process. As of today, using [npm libraries in Ember CLI](https://simplabs.com/blog/2017/02/13/npm-libs-in-ember-cli.html
) still isn't as straightforward and polished and we want it to be.
You can consult our [FAQ on future-proofing](http://emberjs.com/learn/#faq-future-proof) for a more thorough description.

As far as I understand it, there is no plan to remove Bower support in the near future.
What was done in Ember CLI is make Bower no longer a dependency of the project in order to reduce the initial project size, as well as make it "pay go", meaning it is lazily required (pay) only when you actually need it (go). This includes not generating a `bower.json` for a new project in the future, as there are currently no Bower dependencies for a new project.

What was done in Ember itself was to make it into an addon named `ember-source`, like `ember-data`, that is pulled from npm like other addons.
So in that sense, we are consolidating under npm to try to make it consistent across the project dependencies, hence why `bower.json` is now empty.

I'm sorry if the answer seems a bit long, I wanted to try to explain the nuances clearly so I can reference back to post, as many people will probably make similar enquiries.

**Comment by RyanNerd** [comment]
@locks thanks for your lengthy response. It is indeed helpful. I'm going to close this issue. I've set an alarm to create a new issue when 2.13 lands. This way the issue does not become stale. It will indicate that the tutorial no longer references the `bower.json` file. And a part of this will also likely be an update to the _Getting Started_ section as YARN becomes the prefered package/dependency manager. 

Thanks Ember team for the wonderful work that you are all doing! As time permits I will contribute as much as I can. One of the pain points of Ember is the steep learning curve (partly from missing, outdated or inadequate docs and tutorials). I will focus my free time on these efforts to improve this aspect of Ember.

**Comment by acorncom** [comment]
> Thanks Ember team for the wonderful work that you are all doing! As time permits I will contribute as much as I can. One of the pain points of Ember is the steep learning curve (partly from missing, outdated or inadequate docs and tutorials). I will focus my free time on these efforts to improve this aspect of Ember.

@RyanNerd Much appreciated. We'd love to have any/all the help you can manage, looking forward to working with you further
