### ISSUE TITLE
Update Ember tutorial to remove references to application.hbs

### ISSUE THREAD

**Issue by Orbyt** [emberjs/guides#1897]
By default, `ember new` no longer generates `app/templates/application.hbs`. This file is referenced in the official tutorial, found at the bottom of this page: https://guides.emberjs.com/v2.12.0/tutorial/ember-cli/

A similar issue #1491 was posted in 2016, regarding `application.hbs` no longer being generated. Additionally, the default welcome page specifies that the welcome page is included by the `ember-welcome-page` dependency:

`To remove this welcome message, remove the ember-welcome-page add-on from your package.json file`

This part of the tutorial should be removed to prevent confusing new users.

**Comment by Orbyt** [comment]
PR: #1898

**Comment by locks** [comment]
Hi @Orbyt, thank you for reaching out and specially for the PR.

From your description I think you are using an older version of Ember CLI, because this has since be fixed in the blueprint, and we now generate `application.hbs` again. We also changed the strategy of `ember-welcome-page`, and you are now not required to delete the dependency in your `package.json`, only the component in the template.

Can you confirm your version?

**Comment by locks** [comment]
Hi @Orbyt, thank you for reaching out and specially for the PR.

From your description I think you are using an older version of Ember CLI, because this has since be fixed in the blueprint, and we now generate `application.hbs` again. We also changed the strategy of `ember-welcome-page`, and you are now not required to delete the dependency in your `package.json`, only the component in the template.

Can you confirm your version by checking the output of `ember -v`?

**Comment by Orbyt** [comment]
Version of `ember-cli` is `2.10.0`. According to [here](https://ember-cli.com/) the latest version is `2.12.1`. I assume this change was made in between these versions?

As a side note, i've attempted to update my `ember-cli` package several times and keep ending up with `2.10.0`. Uninstalling and reinstalling `ember-cli` produces the same results. Am I missing something?

**Comment by locks** [comment]
It happened in 2.11.0, you can see the [CHANGELOG](https://github.com/ember-cli/ember-cli/blob/master/CHANGELOG.md#2110). It was this PR: https://github.com/ember-cli/ember-cli/pull/6378/files.

**Comment by locks** [comment]
Can you join the Slack channel so someone helps you debug the uninstall/install problem?

**Comment by Orbyt** [comment]
I'll get it resolved. This issue and #1898 are irrelevant if `2.11.0` added this functionality back in. I'll close this comment.
