### ISSUE TITLE
Version dropdown is empty, and a version cannot be selected.

### ISSUE THREAD

**Issue by BWieber** [emberjs/guides#1944]
On the Ember Guides main page, the dropdown appears empty, Options are visible when you select the dropdown, but you cannot choose one. 

<img width="377" alt="empty-dropdown" src="https://cloud.githubusercontent.com/assets/14808841/26216770/49bbef7c-3bd3-11e7-95ce-6447e3fc2e4a.PNG">

**Comment by jenweber** [comment]
Looking into this a little, it is only broken when you’re starting from 2.13. If you go to 2.12 or lower using the url, then switch versions via dropdown, it works until you visit 2.13 again.

Can someone share how guide versions handled, broadly speaking?

**Comment by jenweber** [comment]
@locks how is `versions.current` set, compared to what is in _versions.js.erb? 

While at the url https://guides.emberjs.com/v2.13.0/, setting the value of `versions.current` manually in the browser console allows for normal navigation afterwards:
```
window.GUIDE_VERSIONS.current = "v2.13.0"
```

When `current` is either null or something that is not contained in the versions array, some weird behavior happens. If it's an environmental variable, perhaps it was accidentally set to "2.13.0" instead of "v2.13.0" for example. Another possibility is that the script that sets version.current is now running too early or too late.

**Comment by locks** [comment]
Fixed! Thanks @jenweber for pointing me down the right path.

During the build process in Travis CI we have a script that replaces a string (`CURRENT_VERSION_…`) in one of the JavaScript runtime files where it sets `window.GUIDE_VERSIONS.current`.
However, that script was still trying to load a `firebase.json` file that is no longer present, and the script errors. [Removing those lines](https://github.com/emberjs/guides.emberjs.com/commit/f13c47c0e8ab511d5353fa6d845251e906c2b258) and triggering a Travis CI build (and thus deploy) fixed it.

P.S. We should look into why the error wasn't breaking the build, but alas.
