### ISSUE TITLE
Ember Fixture or Mock Data

### ISSUE THREAD

**Issue by 6button9** [emberjs/guides#2097]
I have tried and tried and tried, but cannot get the Mock or Fixture data to work with Ember Data. Could someone please provide an up to date and complete example.

Please use:
  Routes
  Models
  Controllers
  and Ember CLI

It appears that ember-data is changing faster than the documentation.

Thanks,
John Sutton

**Comment by acorncom** [comment]
hey @6button9, was running over issues and noticed we hadn't responded to this one. Do you have more info on where you were having trouble?  Were you having issues putting mock/fixture data in for tests or was this more for developing your setup initially?

We generally recommend that folks use Ember-CLI-Mirage (which is why it is in the tutorial) as it makes setting up fixture data pretty easy with Ember Data. Is there something else you had in mind?

**Comment by 6button9** [comment]
I cannot recall and have moved on. Ember is not for me. 

On review, I was trying to initialize data form a DS.store through the route model. 

I do greatly appreciate someone replying. 

Thank you,
John Sutton

**Comment by acorncom** [comment]
Noted on the DS.Store stuff. Sorry to hear Ember wasn't for you, we'd always love to have you give it another try! 😉 

I'll close this issue for now
