### ISSUE TITLE
Tutorial tests are inaccurate with 3.x release

### ISSUE THREAD

**Issue by coreycondardo** [emberjs/guides#2239]
I've just started learning ember and am currently going through the guides. The testing sections have a lot of inaccuracies with the move to 3.x and the changes with tests. I believe it would be worth going through all of them in the tutorial and updating to align to the changes made.

**Comment by coreycondardo** [comment]
If this is true (I think it's true, I'm so new I could be completely wrong!), once I finish going through the tutorial I can try to put up a PR to correct the issues I've found.

**Comment by jenweber** [comment]
Hi @coreycondardo can you share a link or two to parts that you think are outdated? A new testing API landed in Ember 3.x, so we almost certainly still have some cleanup to do. Thanks for dropping by to report! Also as you're learning Ember, if you need any help, check out the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) #help channel. You can find the Guides contributors and maintainers in the #-team-learning channel.

**Comment by jtrees** [comment]
This is just one example of many but the code fragment [here](https://github.com/emberjs/guides/blob/a9719c03e58125c095940856c7ef84965428e305/source/tutorial/service.md) (roughly line 267) has some issues:

* Uses `moduleFor` instead of `module` (unlike the default generator output)
* Doesn't use the nested test structure (with the second argument to `module`)
* `this.subject` doesn't work anymore (should we be using `this.owner.lookup` now?)

**Comment by alecha** [comment]
Agree. Another thing that we can update is the use of async/await

**Comment by toddjordan** [comment]
Fixed.
