### ISSUE TITLE
Cookbook recipes that involve ember-cli?

### ISSUE THREAD

**Issue by varblob** [emberjs/guides#248]
Ember NYC is going to be doing a cookbook project night that I'm helping to organize http://www.meetup.com/EmberJS-NYC/events/221989248/  

I'm pulling a list together of recipes from http://discuss.emberjs.com/t/call-to-newbies-and-former-newbies-for-your-cookbook-wishlist/7545

Some of these issues are related to ember-cli, should we avoid references to ember-cli?  I know there is the long term intention to include ember-cli in the guides but that it's not happening yet.

**Comment by trek** [comment]
>  I know there is the long term intention to include ember-cli in the guides but that it's not happening yet.

We're also don't plan on including cookbooks in the 2.0 guides or new recipes in the current guides. This is better handled by the community via blog posts and aggregation (lists like EmberSherpa/Ember Weekly). 

Removing them allows us to focus on the core guide experience and allows the community to experiment with various solutions to more complex problems.

I'd refocus the event on writing a good tutorial article instead of banking on Guide inclusion.

**Comment by varblob** [comment]
Aha, very good to know.  Thanks for getting back quickly.
