### ISSUE TITLE
No guides for 1.13

### ISSUE THREAD

**Issue by vmalloc** [emberjs/guides#389]
The guides on Ember's website point at 1.12, and no 1.13 to be found...

**Comment by F21** [comment]
Would love to see the 1.13 guides published as well.

**Comment by motzyball** [comment]
+1

**Comment by wldcordeiro** [comment]
This should really get updated, with 1.13 being out now it's something bad to drop the ball on.

**Comment by trek** [comment]
Unfortunately feature contributors were a bit, er, hesitant to also submit guide updates for their changes in the 1.13 cycle, so the 1.13 guides aren't as simple as "publish whatever is on master" because master is not significantly different than the 1.12 guides. 

This is less an issue of 1.13 not be *published* than an issue of 1.13 guides not being *authored*. We're in the process of harassing people who authored new features to also fix the guides or collaborate with someone who can help them.

**Comment by vmalloc** [comment]
Thanks for the explanation. I think this is something that would have been nice to have on one of the blog posts about 1.13 and/or the transition to 2.0, to slightly help with the ongoing confusion.

**Comment by vmalloc** [comment]
Also the flurry of deprecations plus the lack of references on how to resolve them is a bit frustrating...

**Comment by trek** [comment]
Deprecations are not part of the guides. They can be found at http://emberjs.com/deprecations/v1.x/

**Comment by tomdale** [comment]
@trek What new features in 1.13 are blocking the guides updates? Let's get a list so we can prioritize them ASAP. @locks @michaelrkn

**Comment by tomdale** [comment]
@trek Given how many users are frustrated when they can't even find 1.13, let's cut 1.13 and issue "patch releases" as new features are added.

**Comment by mixonic** [comment]
closing in favor of https://github.com/emberjs/guides/issues/408
