### ISSUE TITLE
Merge ember-cli.com & emberjs.com guides

### ISSUE THREAD

**Issue by joostdevries** [emberjs/guides#410]
We can start moving content over from ember-cli.com with the goal to merge the two documentations into one. I've split up ember-cli.com into "user guides" and "extending" so we can first focus on the "user guides". Below are some first thoughts on a toc

I propose to add a section to the guide, right under "getting started" called "Developing your app"
- Configuration
- Development server
- Managing dependencies
- Building your app

In getting started, we should add:
- Upgrading

Finally, at the very bottom of the guide, I think a "Common issues" section with dedicated sub-sections (eg. for CLI) would make sense.

**Comment by joostdevries** [comment]
@locks @trek I think we need to agree on the toc before we/others start creating PR's for this.

**Comment by joostdevries** [comment]
cc @tomdale

**Comment by eccegordo** [comment]
Will ember cli ever have anything that approaches the API docs that ember has? Could be useful for addon developers. Not sure if the ember cli source code is instrumented to support automatic generation (e.g. yuidoc stuff). ping @stefanpenner 

As for TOC I think there also needs to be a dedicated section: 

*Getting Started with Node, NPM and Ember CLI*

Some folks know Ember but are new to the node ecosystem so coming into ember cli will be confusing if they don't have some grounding in how it works. Even installing node can be confusing, which is why I personally recommend NVM.

I started some notes in a gist but happy to beta test and contribute to a guide if someone has PR in process for this.

https://gist.github.com/eccegordo/ad908734e7798bf6fa86

**Comment by joostdevries** [comment]
@eccegordo Quite a few modules Ember CLI are actually documented and there is a script to build those docs, I believe we just never got around to actually publishing them. https://github.com/ember-cli/ember-cli/issues/2764

@stefanpenner I think the main issue with the Ember CLI API's is that we might not have all `@private` markers in place and we **don't** want people using private API's in Addons.

**Comment by locks** [comment]
@eccegordo I would rather make the assumptions explicit at the head of the guides and link appropriately to relevant documentation elsewhere, for example: https://docs.npmjs.com/, http://jsmodules.io/, https://babeljs.io/docs/learn-es2015/, https://leanpub.com/exploring-es6/read. I believe "How Ember CLI works with Node and NPM ecosystem" is/will be explained along the guides as we explain how to use it.

@joostdevries mark everything `@private` like Ember.js did and then review as necessary.

**Comment by joostdevries** [comment]
@locks Cool, I can do that. I do think that the addon/blueprint API docs are something we should do **after** the user-guides from Ember-CLI.com are merged.

**Comment by locks** [comment]
I agree

**Comment by eccegordo** [comment]
@locks some links would be adequate. Half the battle is just knowing the terminology and high level architecture so one knows where to go for more research.

Just knowing there is something called babel and transpiling is good for the noob.

:+1: on marking everything as private to get started.

Also I think there needs to be a pretty extensive guide targeting addon developers so synthesizing the  addon hooks document would be a good start.
https://github.com/ember-cli/ember-cli/blob/master/ADDON_HOOKS.md

**Comment by michaelrkn** [comment]
See discussion on https://github.com/emberjs/guides/pull/415#issuecomment-121510696.

**Comment by michaelrkn** [comment]
@joostdevries - We have a goal of getting the 2.0 guides together by Monday, August 3. Do you think you'll be able to have this work ready by then?

**Comment by joostdevries** [comment]
@michaelrkn I hope to. I'll spend some time on this on thursday + saturday. The configuration story for Ember CLI is quite horrible ATM but I'm also in the process of drafting an RFC to simplify that.

**Comment by michaelrkn** [comment]
Awesome, thanks! 

If it helps, here's what I think the high-priority items are:

* Throughout the Guides, add a sentence near the beginning of each relevant section about how to sue the generator for the resource (eg `ember generate model` for the Models section).
* Add a page about the mock server to the Models section
* Update the Testing section as needed.
* General audit of the guides to make sure everything is using Ember CLI properly.

I think `ember new`, `ember server`, and `ember build` will get covered in the Getting Started guide that @poteto and I are working on. 

I'm not totally sure what to do about configuration... I'd say save that for last, especially if you think it's horrible and will change soon :)

And if you can open up several small PRs instead of one big one, that will be very helpful in getting this merged in timely!

**Comment by michaelrkn** [comment]
Awesome work, @joostdevries! We'll be reviewing everything in the next couple days.

**Comment by joostdevries** [comment]
@michaelrkn 515-517 will get some more attention today.

**Comment by michaelrkn** [comment]
This is pretty much done so I'm going to close it out.

**Comment by greyhwndz** [comment]
@michaelrkn: should the 2.0 Guides be using DS.JSONAPIAdapter instead of DS.RESTAdapter?
