### ISSUE TITLE
Create a section for animations/liquid fire

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#448]
@ef4 is doing this.

**Comment by michaelrkn** [comment]
@ef4, any update on this? If it's not going to make it for 2.0, that's okay, just want to get the status.

**Comment by acorncom** [comment]
@michaelrkn I can probably help draft something basic on this that we can flesh out in the future if that'd be helpful ...

**Comment by michaelrkn** [comment]
The idea is to port over http://ef4.github.io/liquid-fire/ into the Guides. @ef4, anything @acorncom can do to help out?

**Comment by ef4** [comment]
Yes. The liquid-fire docs are an Ember app that's built directly from the liquid-fire repo, and I want to keep it that way, because it lets us test every change to liquid-fire against possible breakage in the docs.

So the goal is to integrate the existing Ember app into the guides.emberjs.com domain. There are several possible ways to do this, so somebody just need to experiment and come up with something that works nicely. One idea is:
 - change liquid-fire to deploy it's docs app to `guides.emberjs.com/$VERSION/animation`, instead of `ef4.github.io/liquid-fire`
 - add an "Animation" link to the guides sidebar that goes to `guides.emberjs.com/$VERSION/animation`.
 - style the liquid-fire docs app to match the rest of the guides
 - add a build step for the liquid-fire docs that pulls the header and sidebar from the guides, so it can render them identically.

**Comment by ef4** [comment]
The above is all just the plumbing that's required. There is also editorial work to do too, to change the flow of the docs themselves to be more of a guide. That's where I'm probably needed.

**Comment by acorncom** [comment]
@ef4 Sounds good on the above.  Question re: styling the liquid-fire docs app.  From what I've seen, it sounds like a redesign for the Ember site is in the works in the long-run.  Do you want the liquid-fire guides to use it's own copy of the Ember CSS or should I reference the guides CSS instead?

Seems like a bit of a maintenance headache either way ...

**Comment by locks** [comment]
If you use the guides' CSS then it should get updated when we implement the redesign, no?

**Comment by ef4** [comment]
Yes, it's just likely that somebody changes the guides CSS without noticing
the impact on LF.

But I think that's the best option anyway.

**Comment by acorncom** [comment]
Sounds good.  I'll aim to use guides CSS for LF then.

**Comment by acorncom** [comment]
A few additional thoughts for us to bat around / work through as we think about this:

- [ ] Liquid Fire's left nav bar currently is nested two levels deep (consisting of both main headings and subheadings).  If we add an Animations section (on the main guides area), will we end up with a three-level nav bar (Animations -> Template Helpers -> liquid-outlet)?  This isn't done anywhere else in the guides ...
- [ ] All other guides pages are statically rendered as part of the build process, which allows for a reveal when clicking on a main category.  But because Liquid Fire's main menu is rendered in Ember, we won't be able to keep that same behavior when working with Liquid Fire.

Would we want to embed the LiquidFire test app as an app inside of the Guides (as described here: http://guides.emberjs.com/v2.0.0/configuring-ember/embedding-applications/) ?  Seems like it could cause all sorts of problems (and might not allow enough control for the LiquidFire app to run as desired) ...

But doing so would allow us to create "pages" that correspond to the main LiquidFire "areas" and pre-render the Animation nav bar links for all other pages (instead of having them inaccessible until you click "Animations").

Thoughts?  Am I suggesting all sorts of future pain? :trollface:

**Comment by michaelrkn** [comment]
Tangential note - it would be awesome to get this issue resolved, but it is pretty low-priority compared to [these](https://github.com/emberjs/guides/labels/help%20wanted).

**Comment by acorncom** [comment]
@michaelrkn thanks, will do :+1: Should we change the milestone on this then?  I started pitching in here to help because looked like it was desired soon.  Are we using the "help wanted" label for higher priority items?

**Comment by michaelrkn** [comment]
Good call. Removed the milestone. In general, the things we want help with are labelled "help wanted" :) Otherwise they are likely being worked on by somebody else or low-priority.
