### ISSUE TITLE
Update Models section

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#449]
There is a lot of work to be done to better explain Ember Data and to bring the guides up to date.

**Comment by michaelrkn** [comment]
@locks, can you confirm if you are going to take the lead on this?

**Comment by locks** [comment]
@michaelrkn confirm

**Comment by michaelrkn** [comment]
As part of this, we should also add an explanation of how you can use `$.ajax` to push records into the Ember Data store.

**Comment by greyhwndz** [comment]
Would the new Models section follow the sub-sections found in the currently outdated Models guide?

**Comment by locks** [comment]
> Would the new Models section follow the sub-sections found in the currently outdated Models guide?

Nope.

> It could go to the level of showing the hooks laid in place that others can use to accommodate their case.

I believe we will document how to write custom adapters/serializers to some extent.

**Comment by greyhwndz** [comment]
> I believe we will document how to write custom adapters/serializers to some extent.

What I mean is in the illustration @locks

**Comment by HeroicEric** [comment]
Another thing that I think people run into a lot and should be shown is how to save associated models

**Comment by greyhwndz** [comment]
> Another thing that I think people run into a lot and should be shown is how to save associated models

I agree with this. And I think not just saving but other type of manipulation of the associated models in the context of a collection/list.

**Comment by michaelrkn** [comment]
As noted in #459, on http://guides.emberjs.com/v1.13.0/models/persisting-records/, the second code example under the Promises topic looks almost the same as the first. Let's try to clarify what is going on differently between the two.

**Comment by greyhwndz** [comment]
FWIW, I have asked around forums and our slack channel about their pain points when using Ember Data and also their feedback on the guides. The following are the consolidated concerns that they believe would make it easier on them:

1. Store methods for creating/reading/mutating data in the store
2. when & how Adapter & Serializer methods are invoked by the Store
  * hooks to override them
  * how the ajax request is generated
  * what the format of data each Adapter type expects
  * how the response from server is parsed by Serializers
  * dealing with unconventional formats
3. reading and mutating related models in the context of the different Adapters & Serializers
4. knowing & dealing with Errors from the backend
5. pagination using the different Adapters
6. current best idiom in optimizing requests to the backend (sideloading, coalesce?)
7. knowing the states of model data in the Store
8. forgetting to use .get or .set in related records

**Comment by acorncom** [comment]
@greyhwndz :+1: thanks for compiling that

**Comment by greyhwndz** [comment]
@acorncom You're welcome! :D. The intention is just to let the doc team know what people I have gathered from the community members in our slack channel and in some forums. I asked them about their pain points in going about using Ember Data. We hope that it should not be taken as a demand to really have it that way. The assumption is just that maybe the doc team would be interested to know about what others thinks they need from the documentation/guides based on what they have gone thru attempting to use ED. Many times I also hesitated to try to say about those concerns coz I don't want to sound like conveying is akin to demanding. But then I was thinking I will still attempt to do so under the good intention of contributing. Coz for me when creating the documentation/guides would necessitate knowing what the user of the documentation really need to be able to effectively use the framework we are/have starting to believe in. Nevertheless, I do find the community here as warm, helpful and objective. Definitely worth going forward with. 

Thanks!

**Comment by shaunc** [comment]
btw doc in API and guide on store.push is completely wrong for 2.0 -- it doesn't take `(type, record)`. I have looked through the code and seem to have figured it out for my case, but (though you seem to be doing an extensive rewrite) -- perhaps a hotfix for this issue would be in order?

**Comment by greyhwndz** [comment]
@shaunc It would be really help if you can do a PR on that knowing htat you have already figured the fix :+1:

**Comment by locks** [comment]
It's fixed in master, I believe.

**Comment by shaunc** [comment]
... I just looked at [master of doc](https://github.com/emberjs/guides/blob/master/source/models/pushing-records-into-the-store.md)... hmm... (is this what you meant, or did you mean fixed in master of ember-data?) doc is changed, but:

1) what is the difference between `push` and `pushPayload` ?

2) What worked for me is looking up the jsonapi spec. The new examples don't seem to have that form. (e.g. I needed "data" section and then "attributes" and "relationships" sub-sections; in relationships I needed a type ... very long-winded. It seems setup for "schemaless" use.)

I'm not at all sure how `Store.push` supposed to work (as opposed to how it actually happens to work...), so it would be difficult for me to write a PR. Is `push` supposed to require strict jsonapi? Or, given ember data requires a schema, can we take some shortcuts? Or is ember-data moving to (optionally?) schemaless use? If these questions were answered in sufficient detail, I would be willing to write the a PR, but answering me might be just as hard as writing the doc. :)

**Comment by wecc** [comment]
@shaunc:

`store.push()` accepts a _normalized_ JSON API document. What I mean with _normalized_ is **camelCased** attribute/relationship members and **singular dasherized** types. This is the internal Ember Data JSON API format.

It's important to note that this has nothing to do with the built-in `JSONAPIAdapter/Serializer` which defaults to **dasherized** attribute/relationship members and **plural dasherized** types (to match the examples and recommendations of http://jsonapi.org/ as closely as possible).

`store.pushPayload()` does not care about the format of the payload. Instead it passes the payload to the serializer which has to normalize the payload to the internal Ember Data JSON API format and pass it on to `store.push()`

**Comment by shaunc** [comment]
@wecc -- Thanks! Are both `push` and `pushPayload` still part of the public API?

It also seems a bit of a shame that if we have model `Foo`:

    name: DS.attr('string'),
    bar: DS.belongsTo('bar')

We have to do:

    store.push({
      id: '1', type: 'foo', 
      data: {
        attributes: { name: 'foo' },
        relationships: { bar: { data: { id: '2', type: 'bar' } } }
      }
    });

Rather than:

    store.push({
      id: '1', type: 'foo',
      data: {
        name: 'foo', bar: '2' }
      }
    });

As would be possible given that `store` knows the schema. So I could submit a PR with doc about jsonapi interface, but would prefer to submit a PR to ember-data with simplified format. Which do you prefer? :)

**Comment by wecc** [comment]
> Are both `push` and `pushPayload` still part of the public API?

Confirm.

`store.push()` accepts a JSON API Document conforming to the normalization rules described above. None of your examples are valid JSON API. You would have to do something like this:

```js
store.push({
  data: {
    type: 'foo',
    id: '1',
    attributes: {
      name: 'foo'
    },
    relationships: {
      bar: {
        data: { type: 'bar', id: '2' }
      }
    }
  }
});
```

I believe using `store.pushPayload()` (and `store.normalize()` for single resources) are better options since you delegate the normalization and transformation to JSON API format to the serializer.

Given you're using the `JSONSerializer` or `RESTSerializer` you can simplify the above using:

```js
store.push(store.normalize('foo', { id: 1, name: 'foo', bar: 2 }));
```
