### ISSUE TITLE
[Typo] Section: Configuring Your App

### ISSUE THREAD

**Issue by morganick** [emberjs/guides#626]
https://github.com/emberjs/guides/blob/master/source/configuring-ember/configuring-your-app.md

In the third bullet point, `production` is spelled incorrectly.

**Comment by michaelrkn** [comment]
Thanks for catching all of these typos! For little stuff like this, I think we can get it resolved most quickly if you just open PRs with the appropriate changes. In places where you aren't confident if your recommendation is correct, open a PR anyways and then comment about your uncertainty - if it turns out your change is right, we can just merge it in, and if we need to change something, we can discuss it in the comments there.

**Comment by morganick** [comment]
No problem. I'll create PR's for them later today.
