### ISSUE TITLE
"Understanding Ember.js" Broken Link

### ISSUE THREAD

**Issue by josenberg** [emberjs/guides#671]
There is a broken link on the page (http://guides.emberjs.com/v1.13.0/).
Is the first link in the text, the broken page is http://guides.emberjs.com/v1.13.0/understanding-ember

(Same issue posted now in the correct place: https://github.com/emberjs/website/issues/2332)

**Comment by jornh** [comment]
Looks like the fix is already in the 1.13 branch: https://github.com/emberjs/guides/commit/c27e642cee223bcbc7520d64af7d160968fd61b9 as well as in 2.0.0 where it's already on the site. Apparently all what's needed to fix this is pushing a new 1.13 guide build to http://guides.emberjs.com/v1.13.0/

(For already done reasoning to remove the link altogether see https://github.com/emberjs/guides/pull/444#issuecomment-123529772)

**Comment by locks** [comment]
I'm leaving this open until we redeploy 1.13.

**Comment by michaelrkn** [comment]
I'm redeploying shortly.
