### ISSUE TITLE
Pausing the boot process example doesn't work

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#771]
http://guides.emberjs.com/v2.0.0/services-and-initializers/initializers/#toc_pausing-the-boot-process

`container.lookup('store:main')` is not only private but doesn't work in 2.0. 

Can someone come up with another example to use here?

**Comment by locks** [comment]
I believe you simply can't defer readiness, so this section would be removed.

**Comment by mattmarcum** [comment]
@locks you can defer readiness in an application initializer but not in an instance initializer.  I think these concepts have not been documented in the guides or api at all.  I can't even figure out where this stuff is in the api at all.  The only thing I've been able to find is a blog post, but it doesn't work in ember2.0 either: http://emberjs.com/blog/2015/05/13/ember-1-12-released.html#toc_instance-initializers

The example in the guide is for an application initializer - I can tell because the path is `app/initializers`.  If it was an instance initializer then it would be `app/instance-initializers`.  

I think the signature for app initializers has changed and needs to be documented.  I'm guessing that it is now `function(registry, application)`.  Here is a version of the example that I got working...however I need confirmation that this is correct:

```javascript 
export default {
  name: "currentUserLoader",
  after: "store",

  initialize: function(registry, application) {
    application.deferReadiness();

    registry.container().lookup('service:store').find('user', 'current').then(function(user) {
      application.inject('route', 'currentUser', 'user:current');
      application.advanceReadiness();
    });
  }
};
```

I'm assuming the first arg is a `Registry` based on the class name, but I can't find any docs to support this. I also had to guess at how to get the container via a method invocation.  It works however...so there is that.

**Comment by mattmarcum** [comment]
Update: for ember 2.0.2 I found the code that call the different initializers:

https://github.com/emberjs/ember.js/blob/v2.0.2/packages/ember-application/lib/system/application.js#L679

so it looks like the signature for app initializers is `function(registry, app)` like I assumed and for instance initializers it is just `function(instance)`

Hope that helps - it would be great to get both initializer types into the guides.

One last thing - there is a feature named `ember-registry-container-reform` that is going to change this - probably in ember2.1 - https://github.com/emberjs/ember.js/blob/v2.1.0-beta.4/packages/ember-application/lib/system/application.js#L605

There the signature for app initializer is just `function(app)` and the signature for instance initializer is `function(instance)`
