### ISSUE TITLE
Guides should remove references to Ember.ObjectController

### ISSUE THREAD

**Issue by mikepmunroe** [emberjs/guides#81]
There is at least one known usage in https://github.com/emberjs/guides/blob/master/source/templates/actions.md, but we should scan other files for usage, as well.

Here is some reference documentation, http://emberjs.com/guides/deprecations/#toc_objectcontroller

**Comment by Serabe** [comment]
`ObjectController` is referenced in ~13 different guides with no more than 25 occurrences. Some of them just require removing the `Object` part, others might require a couple of lines of code more and few might require minor rephrasing.

If @trek is fine with this change, I can do it tomorrow night (UTC+1 time).

**Comment by rwjblue** [comment]
Yes, please audit for usage of ObjectController and update.

**Comment by Serabe** [comment]
I'll continue tomorrow. I had reduced the number of occurrences down to 7 in 5 different files. If everything goes ok, I'll finish this tomorrow.

**Comment by Serabe** [comment]
I think this issue cannot be totally resolved. I left a couple of mentions untouched since they are about the controllers autogenerated by Ember when one cannot be found.

I see a couple options here:

* Left the files as they are now.
* Add a deprecation warning.

I think the latter is the way to go. Any hint?

**Comment by rwjblue** [comment]
Even when Ember auto-generates an ObjectController a deprecation is fired if you use its proxying abilities (`firstName` will deprecate but `model.firstName` will not).

**Comment by Serabe** [comment]
In first place, sorry for taking me so long to come back to this issue. I've been sick in bed and even now I cannot spend too much time in front of my computer.

About the issue, I know that the deprecation warning is still there. Since Ember.js does generates an ObjectController when no explicit controller is found, I think keeping the documentation about that fact but adding a deprecation warning in the guides is the way to go.

I wouldn't remove these references because Ember is still generating an ObjectController and people can easily forget to type `model.` in front of the property (or they are following a tutorial, or they are looking at the old Ember.js Todo app, etc.). Adding a deprecation warning will help people know that that is undesired behaviour while letting others know what is happening with that _magic_ controller they didn't write.

**Comment by trek** [comment]
closing in favor of #90
