### ISSUE TITLE
Include imports in code snippets

### ISSUE THREAD

**Issue by HeroicEric** [emberjs/guides#883]
I see that the decision was made to remove all imports in https://github.com/emberjs/guides/pull/580

I think this causes a lot of confusion for people trying to get started by following the examples in the guides. Not sure I understand why the decision was to omit the code that people actually need to make the snippets work.

For example, I want to learn how to pass a property to a component and I am presented with:

![](https://dl.dropboxusercontent.com/spa/ibxdnt7kjmsxult/m6xq_m22.png)

Unless I use the generator to create my route, just using what's shown in that snippet is going to cause me issues before I even get to the component part.

**Comment by locks** [comment]
Using the generator is encouraged throughout the guides, so the expectation is that people will mostly understand when a code sample is partial. I have some ideas how to signal this better.

I'm closing this issue because we already have a plan to address the matter when the final modules land, which is still TBD.
