### ISSUE TITLE
Add spell checking as an optional failing test for our Travis build

### ISSUE THREAD

**Issue by acorncom** [emberjs/guides#948]
Best bet might be to use Hunspell (http://hunspell.sourceforge.net), but other suggestions welcome.

It'd also be nice to be able to make automated suggestions over time (as outlined here: http://minds.coremedia.com/2014/02/17/automated-documentation-check-with-languagetool/)

**Comment by michaelrkn** [comment]
Preferably this would also raise an exception when using the development server, so that contributors can get feedback as they're working.

**Comment by locks** [comment]
:+1: :+1: :+1: :+1: :+1:

**Comment by mwils** [comment]
I think I would like to take a stab at this.

**Comment by mwils** [comment]
I am working on a solution. I will run Aspell via Middleman in order to satisfy @michaelrkn's suggestion.

**Comment by mwils** [comment]
I have the spell checker working. I just need to fix some false hits and I will be good to push it.

**Comment by michaelrkn** [comment]
Awesome @mwils! Can't wait to see it.

**Comment by mwils** [comment]
Been a busy past few days. I hope to get some time to work on this soon.

**Comment by mwils** [comment]
I am using a for the spell check, but I had to make some mods (read hacks) to the gem in order to remove some false positives and also I had to fix a bug. I made a pull request (pending) to the repo owner for the bug, however I am not sure if the other code would make sense to include in the spellchecker main repo.

My questions are:
1. Should I just point the Guides Gemfile at my repo forked repo with the custom code and bug fix or should I use an initializer within the Guide code to make the changes?
https://github.com/mwils/middleman-spellcheck/commit/c1d66c7a03c672c7e62a9f6b5c079f832d18bdba
and
https://github.com/mwils/middleman-spellcheck/commit/2e2331b06431dd56f939827ab86d58b1cde305f5

2. I have an array with ~285 words that are not in aspell's dictionary that need to be allowed. Contributors might need to add words to this from time to time. Right now I just have that array throw into the `config.rb`, but it should probably be somewhere else. Where do you all suggest?
https://github.com/mwils/guides/commit/ea54231e8d11470023677d9d8040a6b7d01789ad

3. My implementation will add `aspell` as a build dependency. `brew install aspell` will do the trick. Is this ok(to require a dependency)?

I will add the appropriate notes into the readme once its all worked out as well.

Disclaimer - This is the first time I've touched ruby code. :)

**Comment by michaelrkn** [comment]
Thanks for getting this going @mwils!

1. The ideal thing would be to get your changes merged into the original repo. The `if` statement fix looks pretty straightforward and general-purpose, so hopefully that can get merged in easily. Ignoring anything in the `table.CodeRay` class seems pretty specific to our project, though - maybe you can add an option to skip spell checking based on element and class/id to the project, so that then we can just initialize the library appropriately from our code? Also, why do we need to ignore all words in single quotes?
2. I'm actually not sure the best place for the array. Maybe in a file in the `lib` folder? Maybe just in a root-level file called `spelling-exceptions.rb` that then you can `require` from `config.rb`?
3. My cursory glance around the internet (which I suppose you have done as well) suggests this is unavoidable for spell-checking. Can you update the readme to note the dependency?

**Comment by mwils** [comment]
1. Yes it is a good idea to make that a configurable option. I will do that and make a pull request
2. Sounds good
3. Will do
And your welcome. I've enjoyed learning about gems and ruby in general.
